#!/usr/bin/env python3
"""Keep this skill in sync with https://github.com/tidyverse/style.

Two layers are kept in sync, and they are checked separately:

1. ``references/*.md`` -- a lossless, mechanical conversion of every chapter
   in the upstream Quarto book. Regenerated by this script; never hand-edit.
2. ``SKILL.md`` -- the hand-compacted version of the whole guide. It records
   the upstream commit it was compacted from in its frontmatter
   (``metadata.upstream_commit``). When upstream moves, this script prints
   the diff of the chapters that changed so the compaction can be updated,
   then ``--mark`` stamps the new commit into SKILL.md.

Usage
-----
    python scripts/sync.py            # fetch upstream, regenerate references/, report
    python scripts/sync.py --check    # exit 1 if references/ or SKILL.md are behind upstream
    python scripts/sync.py --mark     # after updating SKILL.md: record current upstream commit
    python scripts/sync.py --offline  # skip the network fetch, use the local clone as-is

Only the standard library and a ``git`` executable are required.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

UPSTREAM_URL = "https://github.com/tidyverse/style.git"
ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = ROOT / "upstream"          # shallow clone, gitignored
REFS = ROOT / "references"
STATE = REFS / "UPSTREAM.json"
SKILL = ROOT / "SKILL.md"


# --------------------------------------------------------------------------- git
def git(*args: str, cwd: Path = UPSTREAM) -> str:
    return subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True
    ).stdout.strip()


def fetch_upstream(offline: bool) -> None:
    if not (UPSTREAM / ".git").exists():
        if offline:
            sys.exit(f"error: no local clone at {UPSTREAM} and --offline given")
        print(f"cloning {UPSTREAM_URL} -> {UPSTREAM.relative_to(ROOT)}/")
        subprocess.run(
            ["git", "clone", "-q", "--depth", "1", UPSTREAM_URL, str(UPSTREAM)],
            check=True,
        )
    elif not offline:
        # Keep full history of main so we can diff between recorded commits.
        git("fetch", "-q", "--unshallow", "origin") if is_shallow() else git("fetch", "-q", "origin")
        git("reset", "-q", "--hard", "origin/HEAD")


def is_shallow() -> bool:
    return git("rev-parse", "--is-shallow-repository") == "true"


def head() -> dict:
    sha, date, subject = git("log", "-1", "--format=%H%n%cI%n%s").split("\n", 2)
    return {"commit": sha, "date": date, "subject": subject}


# ------------------------------------------------------------------- conversion
def chapters() -> list[str]:
    """Chapter file stems in book order, read from _quarto.yml."""
    text = (UPSTREAM / "_quarto.yml").read_text(encoding="utf-8")
    return re.findall(r"^\s*-\s*(?:chapters:\s*)?-?\s*([\w-]+)\.qmd\s*$", text, re.M)


def collect_anchors(stems: list[str]) -> dict[str, tuple[str, str]]:
    """Map every heading id (explicit ``{#id}`` or implicit slug) -> (file, title)."""
    anchors: dict[str, tuple[str, str]] = {}
    for stem in stems:
        for line in (UPSTREAM / f"{stem}.qmd").read_text(encoding="utf-8").splitlines():
            m = re.match(r"^(#+)\s+(.*?)\s*(?:\{#([\w-]+)\})?\s*(?:\{-\})?\s*$", line)
            if not m:
                continue
            title = m.group(2).strip()
            if m.group(3):
                anchors[m.group(3)] = (stem, title)
            anchors.setdefault(slug(title), (stem, title))
    return anchors


def slug(title: str) -> str:
    return re.sub(r"[^\w]+", "-", title.lower().strip("`")).strip("-")


def convert(stem: str, anchors: dict[str, tuple[str, str]], sha: str) -> str:
    src = (UPSTREAM / f"{stem}.qmd").read_text(encoding="utf-8")
    out: list[str] = []
    in_chunk = False
    in_callout = False
    for line in src.splitlines():
        # Code fences: ```{r} / ```R / ``` -> ```r ; drop `#|` chunk options.
        if re.match(r"^\s*```\{r[^}]*\}\s*$", line) or re.match(r"^\s*```R\s*$", line):
            in_chunk = True
            out.append(re.sub(r"```.*$", "```r", line))
            continue
        if in_chunk:
            if re.match(r"^\s*```\s*$", line):
                in_chunk = False
                out.append(line)
            elif re.match(r"^\s*#\|", line):
                continue
            else:
                out.append(line)
            continue
        # Headings: strip {#id} and {-} attributes.
        line = re.sub(r"\s*\{#[\w-]+\}\s*$", "", line)
        line = re.sub(r"\s*\{-\}\s*$", "", line)
        # Quarto callouts -> blockquote.
        m = re.match(r"^:::\s*\{\.callout-(\w+)\}", line)
        if m:
            out.append(f"> **{m.group(1).capitalize()}:**")
            in_callout = True
            continue
        if line.strip() == ":::":
            in_callout = False
            continue
        if in_callout:
            out.append("> " + line if line.strip() else ">")
            continue
        # Cross references @sec-id -> [Title](file.md)
        line = re.sub(
            r"@sec-([\w-]+)",
            lambda m: xref("sec-" + m.group(1), anchors),
            line,
        )
        # Local anchor links (#id) -> (file.md#slug)
        line = re.sub(
            r"\]\(#([\w-]+)\)",
            lambda m: "](" + xref_target(m.group(1), anchors) + ")",
            line,
        )
        out.append(line)

    text = "\n".join(out)
    # Drop Quarto/HTML editor notes (<!--# ... -->), which are upstream to-dos,
    # not guidance. Ordinary HTML comments are kept.
    text = re.sub(r"<!--#.*?-->\n?", "", text, flags=re.S)
    # Drop knitr-only chunks that render images (index.qmd's styler screenshot).
    text = re.sub(r"```r\n\s*knitr::include_graphics\([^\n]*\)\n\s*```\n?", "", text)
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text).strip() + "\n"

    header = (
        f"<!-- Generated by scripts/sync.py from "
        f"https://github.com/tidyverse/style/blob/{sha}/{stem}.qmd -- do not edit. "
        f"Licence: CC BY-SA 3.0, (c) the tidyverse team. -->\n\n"
    )
    return header + text


def xref(anchor_id: str, anchors: dict[str, tuple[str, str]]) -> str:
    if anchor_id in anchors:
        stem, title = anchors[anchor_id]
        return f"[{title}]({stem}.md)"
    return anchor_id


def xref_target(anchor_id: str, anchors: dict[str, tuple[str, str]]) -> str:
    if anchor_id in anchors:
        stem, title = anchors[anchor_id]
        return f"{stem}.md#{slug(title)}"
    return "#" + anchor_id


def regenerate(sha: str) -> list[str]:
    stems = chapters()
    anchors = collect_anchors(stems)
    REFS.mkdir(exist_ok=True)
    written = []
    for stem in stems:
        target = REFS / f"{stem}.md"
        target.write_text(convert(stem, anchors, sha), encoding="utf-8", newline="\n")
        written.append(target.name)
    # Remove chapters that no longer exist upstream.
    for stale in REFS.glob("*.md"):
        if stale.name not in written and stale.name != "README.md":
            stale.unlink()
            print(f"removed {stale.relative_to(ROOT)} (chapter dropped upstream)")
    return stems


# ------------------------------------------------------------------- SKILL.md
FM_KEY = "upstream_commit"


def skill_commit() -> str | None:
    if not SKILL.exists():
        return None
    text = SKILL.read_text(encoding="utf-8")
    m = re.search(rf"^\s*{FM_KEY}:\s*([0-9a-f]{{7,40}})\s*$", text, re.M)
    return m.group(1) if m else None


def mark_skill(sha: str) -> None:
    text = SKILL.read_text(encoding="utf-8")
    if re.search(rf"^\s*{FM_KEY}:", text, re.M):
        text = re.sub(rf"^(\s*{FM_KEY}:\s*)[0-9a-f]+", rf"\g<1>{sha}", text, flags=re.M)
    else:
        sys.exit(f"error: SKILL.md frontmatter has no `metadata.{FM_KEY}` key to update")
    SKILL.write_text(text, encoding="utf-8", newline="\n")
    print(f"SKILL.md: {FM_KEY} = {sha}")


def report_skill_drift(sha: str) -> bool:
    """Print what changed upstream since SKILL.md was compacted. True if stale."""
    recorded = skill_commit()
    if recorded is None:
        print(f"SKILL.md: no `{FM_KEY}` recorded -- treat as stale")
        return True
    if sha.startswith(recorded) or recorded.startswith(sha):
        print(f"SKILL.md: up to date with upstream {sha[:10]}")
        return False
    print(f"\nSKILL.md was compacted from {recorded[:10]}; upstream is now {sha[:10]}.")
    try:
        stat = git("diff", "--stat", f"{recorded}..{sha}", "--", "*.qmd", "_quarto.yml")
    except subprocess.CalledProcessError:
        print("  (recorded commit not in local history -- run without --offline to unshallow)")
        return True
    if not stat:
        print("  No chapter text changed (only non-content files). Run --mark to accept.")
        return False
    print("  Changed chapters:\n" + "\n".join("    " + l for l in stat.splitlines()))
    print(f"\n  Full diff, to fold into SKILL.md:\n"
          f"    git -C upstream diff {recorded[:10]}..{sha[:10]} -- '*.qmd'\n"
          f"  Then: python scripts/sync.py --mark")
    return True


# ------------------------------------------------------------------------ main
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if anything is behind upstream")
    ap.add_argument("--mark", action="store_true", help="record current upstream commit in SKILL.md")
    ap.add_argument("--offline", action="store_true", help="do not fetch; use the local clone")
    args = ap.parse_args()

    fetch_upstream(args.offline)
    info = head()
    sha = info["commit"]
    print(f"upstream: {sha[:10]} {info['date'][:10]} \"{info['subject']}\"")

    if args.mark:
        mark_skill(sha)
        return 0

    old_state = json.loads(STATE.read_text(encoding="utf-8")) if STATE.exists() else {}
    refs_stale = old_state.get("commit") != sha

    if args.check:
        if refs_stale:
            print(f"references/: generated from {old_state.get('commit', 'nothing')[:10]} -- STALE")
        else:
            print(f"references/: up to date")
        skill_stale = report_skill_drift(sha)
        return 1 if (refs_stale or skill_stale) else 0

    stems = regenerate(sha)
    STATE.write_text(
        json.dumps(
            {
                **info,
                "url": UPSTREAM_URL,
                "synced_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                "chapters": stems,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"references/: regenerated {len(stems)} chapters from {sha[:10]}")
    report_skill_drift(sha)
    return 0


if __name__ == "__main__":
    sys.exit(main())
